name: Build Firefox Extension

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy extension files (excluding .git, .github, dist)
      run: |
        mkdir -p dist
        rsync -av --exclude='.git' --exclude='.github' --exclude='dist' ./ dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ip2whois-firefox
        path: dist/